// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDniNdqjrR1isW4f4PPDgN121onI0TEfF8',
    appId: '1:715590338204:web:f2b3eef707d93ee539cf59',
    messagingSenderId: '715590338204',
    projectId: 'umkm-cashier',
    authDomain: 'umkm-cashier.firebaseapp.com',
    storageBucket: 'umkm-cashier.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD052HA9OSumsfjwLJ8why-ewUmil7IDQE',
    appId: '1:715590338204:android:3c9f35a12077fff239cf59',
    messagingSenderId: '715590338204',
    projectId: 'umkm-cashier',
    storageBucket: 'umkm-cashier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsZSvBap6P0g7SLSIsKI-wojK93_sGTkw',
    appId: '1:715590338204:ios:d2a45903edb61cf539cf59',
    messagingSenderId: '715590338204',
    projectId: 'umkm-cashier',
    storageBucket: 'umkm-cashier.firebasestorage.app',
    iosBundleId: 'com.example.umkmEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsZSvBap6P0g7SLSIsKI-wojK93_sGTkw',
    appId: '1:715590338204:ios:d2a45903edb61cf539cf59',
    messagingSenderId: '715590338204',
    projectId: 'umkm-cashier',
    storageBucket: 'umkm-cashier.firebasestorage.app',
    iosBundleId: 'com.example.umkmEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDniNdqjrR1isW4f4PPDgN121onI0TEfF8',
    appId: '1:715590338204:web:3bbe459b52fbc1e639cf59',
    messagingSenderId: '715590338204',
    projectId: 'umkm-cashier',
    authDomain: 'umkm-cashier.firebaseapp.com',
    storageBucket: 'umkm-cashier.firebasestorage.app',
  );
}
